run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - copyloopvar
    - govet
    - gosimple
    - gofmt
    - gofumpt
    - goconst
    - goimports
    - mnd
    - gocyclo
    - ineffassign
    - lll
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace
    - wastedassign
    - unconvert
    - misspell
    - errorlint
    - errname
    - goheader
    - zerologlint
    - tagliatelle
    - spancheck
    - perfsprint
    - promlinter
    - predeclared
    - nestif
    - nilnil
    - makezero
    - grouper
    - gosec
    - dupl
    - cyclop
    - copyloopvar

linters-settings:
  govet:
    enable-all: true
  whitespace:
    multi-func: true
  lll:
    line-length: 160
  # mnd:
  #   checks:
  #     - case
  #     - condition
  #     - return
  goconst:
    ignore-tests: true
  gocyclo:
    # recommend 10-20
    min-complexity: 50
  goimports:
    local-prefixes: github.com/almeidapaulopt/tsdproxy # Put imports beginning with prefix after 3rd-party packages
  misspell: # Finds commonly misspelled English words in comments
    locale: US
  goheader:
    values:
      const:
        AUTHOR: Paulo Almeida <almeidapaulopt@gmail.com>
    template: |-
      SPDX-FileCopyrightText: {{ YEAR }} {{ AUTHOR }}
      SPDX-License-Identifier: MIT
