# SPDX-FileCopyrightText: 2024 Paulo Almeida <almeidapaulopt@gmail.com>
# SPDX-License-Identifier: MIT

version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GITHUB_ORG=almeidapaulopt
  - DOCKER_ORG=almeidapaulopt
  - DOCKERFILE=Dockerfile.goreleaser

before:
  hooks:
    - go mod tidy
    - go generate ./...

gomod:
  proxy: false

report_sizes: true

builds:
  - id: server
    main: ./cmd/server/main.go
    binary: tsdproxyd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
    ldflags:
      - -s -w -X "github.com/almeidapaulopt/tsdproxy/internal/core.buildString={{ .Branch }} ({{ .ShortCommit }} {{ .Date }}, {{ .Os }}/{{ .Arch }})" -X "github.com/almeidapaulopt/tsdproxy/core.version={{ .Branch }}"

  - id: healthcheck
    main: ./cmd/healthcheck/main.go
    binary: healthcheck
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd

universal_binaries:
  - replace: false

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
    allow_different_binary_count: true

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: "{{ .Env.DOCKERFILE }}"
    image_templates:
      - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Branch }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Branch }}-amd64"
    build_flag_templates:
      - "--pull"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Paulo Almeida","email":"almeidapaulopt@gmail.com"}]'
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: "{{ .Env.DOCKERFILE }}"
    image_templates:
      - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Branch }}-arm64v8"
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Branch }}-arm64v8"
    build_flag_templates:
      - "--pull"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Paulo Almeida","email":"almeidapaulopt@gmail.com"}]'
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/arm64/v8"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    dockerfile: "{{ .Env.DOCKERFILE }}"
    image_templates:
      - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Branch }}-armv6"
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Branch }}-armv6"
    build_flag_templates:
      - "--pull"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Paulo Almeida","email":"almeidapaulopt@gmail.com"}]'
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/arm/v6"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: "{{ .Env.DOCKERFILE }}"
    image_templates:
      - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Branch }}-armv7"
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Branch }}-armv7"
    build_flag_templates:
      - "--pull"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Paulo Almeida","email":"almeidapaulopt@gmail.com"}]'
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/arm/v7"

docker_manifests:
  - name_template: "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Branch }}"
    image_templates:
      - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Branch }}-amd64"
      - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Branch }}-arm64v8"
      - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Branch }}-armv6"
      - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Branch }}-armv7"
  - name_template: ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Branch }}
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Branch }}-amd64
      - ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Branch }}-arm64v8
      - ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Branch }}-armv6
      - ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Branch }}-armv7

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - --yes
