# SPDX-FileCopyrightText: 2024 Paulo Almeida <almeidapaulopt@gmail.com>
# SPDX-License-Identifier: MIT

version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GITHUB_ORG=almeidapaulopt
  - DOCKER_ORG=almeidapaulopt
  - DOCKERFILE=Dockerfile.goreleaser
  - LATEST={{ if .Env.LATEST_TAG }}{{ .Env.LATEST_TAG }}{{ else }}dev{{ end }}

before:
  hooks:
    - bun i --cwd ./web
    - bun run --cwd web build
    - sh -c 'go install github.com/a-h/templ/cmd/templ@$(go list -m github.com/a-h/templ | awk "{print \$2}")'
    - go generate ./...

report_sizes: true

snapshot:
  version_template: "{{ incpatch .Version }}-{{ .Env.LATEST }}"

release:
  make_latest: false
  mode: replace
  prerelease: true
  draft: true
  replace_existing_draft: true
  skip_upload: true

builds:
  - id: server
    main: ./cmd/server/main.go
    binary: tsdproxyd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
    ldflags:
      - -s -w
      - -X "github.com/almeidapaulopt/tsdproxy/internal/core.version={{ incpatch .Version }}-{{ .Env.LATEST }}"
      - -X "tailscale.com/version.Short={{ .Env.TAILSCALE_VERSION }}"
      - -X "tailscale.com/version.Long={{ .Env.TAILSCALE_VERSION }}-TSDProxy"
      - -X "tailscale.com/version.GitCommit={{ .ShortCommit }}"
      - -X "tailscale.com/version.shortStamp={{ .Env.TAILSCALE_VERSION }}"
      - -X "tailscale.com/version.longStamp={{ .Env.TAILSCALE_VERSION }}-TSDProxy"
      - -X "tailscale.com/version.gitCommitStamp={{ .ShortCommit }}"

  - id: healthcheck
    main: ./cmd/healthcheck/main.go
    binary: healthcheck
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd

universal_binaries:
  - replace: false

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

archives:
  - formats: tar.gz
    files:
      - README.md
      - LICENSE
    allow_different_binary_count: true

dockers_v2:
  - dockerfile: "{{ .Env.DOCKERFILE }}"
    ids:
      - server
      - healthcheck
    images:
      - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}"
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
    tags:
      - "{{ .Env.LATEST }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7
    labels:
      "io.artifacthub.package.maintainers": '{"name":"Paulo Almeida","email":"almeidapaulopt@gmail.com"}'
      "io.artifacthub.package.license": "MIT"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{ incpatch .Version }}-{{ .Env.LATEST}}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "{{ .ProjectName }}"
      "org.opencontainers.image.url": "https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}"
      "org.opencontainers.image.source": "{{.GitURL}}"

docker_signs:
  - args:
      - "sign"
      - "${artifact}@${digest}"
      - --yes
