[tools]
air = "latest"
"aqua:a-h/templ" = "latest"
bun = "latest"
go = "latest"
golangci-lint = "latest"
goreleaser = "latest"
hugo = "latest"
"npm:vite" = "latest"
fnox = "latest"


[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"


[env]
_.fnox-env = { tools = true }
