services:
  c1:
    image: nginx
    ports:
      - 91:80
      - 92:8000
      - 93:8080
    deploy:
      labels:
        - tsdproxy.enable=true
        - tsdproxy.name=testeff
        - tsdproxy.ephemeral=true
        - tsdproxy.funnel=true
        - tsdproxy.container_port=80
    networks:
      - c1

  c2:
    image: nginx
    ports:
      - 82:80
    deploy:
      labels:
        - tsdproxy.enable=true
    networks:
      - c2

  c3:
    image: nginx
    network_mode: host
    # ports:
    #   - 83:80
    deploy:
      labels:
        - tsdproxy.enable=true

volumes:
  tsdata:
  tmp:

networks:
  c1:
  c2:
