services:
  tailscale-docker-proxy:
    image: tsdproxy:latest
    container_name: tailscale-docker-proxy
    ports:
      - "8080:8080"
    volumes:
      - tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
    environment:
      - TSDPROXY_AUTHKEYFILE=/run/secrets/authkey
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TSDPROXY_LOG_LEVEL=trace
    secrets:
      - authkey
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=dash-dev

  c1:
    image: nginx
    ports:
      - 81:80
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=teste
    networks:
      c1:

  c2:
    image: nginx
    ports:
      - 82:80
    networks:
      c2:
    labels:
      - tsdproxy.enable=true

  c3:
    image: nginx
    ports:
      - 83:80
    networks:
      c3:
    labels:
      - tsdproxy.enable=true

volumes:
  tsdata:
  tmp:

secrets:
  authkey:
    file: ./KEY_FILE

networks:
  c1:
    name: c1
  c2:
    name: c2
  c3:
    name: c3
