services:
  dev:
    image: devimage
    ports:
      - "8080:8080"
      - "7331:7331"
    volumes:
      - ..:/app
      - .:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=dash-dev
      - tsdproxy.dash.visible=false
    restart: unless-stopped
    secrets:
      - authkey

secrets:
  authkey:
    file: ./KEY_FILE

volumes:
  tmp:
  data:
