services:
  tailscale-docker-proxy:
    image: tsdproxy:latest
    container_name: tailscale-docker-proxy
    ports:
      - "8080:8080"
    volumes:
      - tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
    environment:
      - TSDPROXY_AUTHKEYFILE=/run/secrets/authkey
      - TSDPROXY_DATADIR:/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    secrets:
      - authkey

  c1:
    image: nginx
    # ports:
    #   - 81:80
    labels:
      - tsdproxy.enable=true
      # - tsdproxy.url=https://localhost:8081
      # - tsdproxy.proxy.port=8081

  c2:
    image: nginx
    # ports:
    # - 82:80
    # labels:
    #   - tsdproxy.enable=true
    # - tsdproxy.proxy.port=8082

  c3:
    image: nginx
    network_mode: host
    ports:
      - 83:80
    # labels:
    # - tsdproxy.enable=true
    # - tsdproxy.proxy.port=8083

volumes:
  tsdata:
  tmp:

secrets:
  authkey:
    file: ./KEY_FILE
